import { Footer } from '@/components/footer/Footer'
import { Header } from '@/components/header'
import { rosario } from '@/fonts'
import { cn } from '@/lib/utils'
import type { Metadata } from 'next'
import './globals.css'

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='en'>
			<body className={cn(rosario.className, 'flex flex-col h-screen')}>
				<Header />
				{children}

				<Footer />
			</body>
		</html>
	)
}
